spring:
  mustache:
    servlet:
      exposed-request-attributes: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/jwt_prac_db?serverTimezone=Asia/Seoul
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  output:
    ansi:
      enabled: always

jwt:
  secret-key: ba223661e3ddf6a551e8a586e221069222f41c702923ce8f0b2bd313ac97c9884ae78275e3c571767d50fbfbb16f6aaaaa
  access-expire-time: 600000 # 10분
  refresh-expire-time: 86400000 # 1일